language: csharp
solution: PhoneBook.sln
before_install:
  - curl -s -o $HOME/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh
  - source $HOME/.nvm/nvm.sh
  - nvm install stable
  - node --version
install:
  - nuget restore PhoneBook.sln
  - cd PhoneBook.Core
  - npm install
